services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - backend-network
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 450m
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      ROCKETMQ_NAME_SERVER: namesrv:9876
    depends_on:
      - namesrv
      - broker
      - kafka-zookeeper
      - kafka

  namesrv:
    container_name: rocketmq-namesrv
    image: apache/rocketmq:5.4.0
    environment:
      JAVA_OPT_EXT: -server -Xms256m -Xmx256m -Xmn256m
    networks:
      - backend-network
    ports:
      - 9876:9876
    command: sh ./mqnamesrv

  broker:
    container_name: rocketmq-broker
    image: apache/rocketmq:5.4.0
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: -server -Xms512m -Xmx512m -Xmn256m
      BROKER_CONF: |
        brokerClusterName = MinimalCluster
        brokerName = broker-a
        brokerId = 0
        deleteWhen = 04
        fileReservedTime = 48
        brokerRole = ASYNC_MASTER
        flushDiskType = ASYNC_FLUSH
        brokerIP1=0.0.0.0
    networks:
      - backend-network
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    command: |
      bash -c '
      mkdir -p /home/rocketmq/conf && 
      echo "$$BROKER_CONF" > /home/rocketmq/conf/broker.conf && 
      ./mqbroker -c /home/rocketmq/conf/broker.conf
      '

  # Kafka
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.9.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend-network
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.9.6
    depends_on:
      - kafka-zookeeper
    networks:
      - backend-network
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      # Где Kafka реально слушает внутри контейнера
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      # Какие адреса Kafka отдаёт клиентам
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  kafka_data:
    driver: local

networks:
  backend-network:
    driver: bridge
